- name: configure redis component
  hosts: user
  become: yes
  tasks:
  - name : Disable current redis
    ansible.builtin.command: dnf module disable redis -y

  - name : enable current redis
    ansible.builtin.command: module enable redis:7 -y

  - name : Install redis
    ansible.builtin.dnf: 
      name: redis
      state: present
  - name: Allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0.'
  - name: update protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis 
    ansible.builtin.service:
      name: redis 
      state: started
      enabled: yes